server:
  port: 8080
spring:
  config:
    import: classpath:myconfig.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    tryItOutEnabled: true